// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waewsflswlcdrbsexeph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhZXdzZmxzd2xjZHJic2V4ZXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzE1NzgsImV4cCI6MjA2OTk0NzU3OH0.4OgfvJHtGOZNKUDOYQmndh9-w2pcEf_EYoT_Lc5uJWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});